import type {
  DetectRegions,
  DetectResult,
  ImageWatermarkParams,
  VideoWatermarkParams,
} from "@/domain/schemas";

/** Health snapshot of the omniwm sidecar, surfaced to the UI for degradation. */
export type SidecarHealth = {
  ok: boolean;
  ffmpeg: boolean;
  ffprobe: boolean;
  face: boolean;
  mediaDirWritable: boolean;
  version: string;
};

export type WatermarkOptions = {
  abortSignal?: AbortSignal;
};

/**
 * Contract for the watermark capability. The infrastructure adapter implements
 * this as a thin HTTP client to the FastAPI sidecar. Convention-aligned with the
 * other domain ports; not a replaceability seam (one implementation only).
 *
 * All paths are absolute, inside MEDIA_DIR, generated by the application layer.
 */
export interface WatermarkPort {
  health(options?: WatermarkOptions): Promise<SidecarHealth>;

  watermarkImage(
    input: { inDir: string; outDir: string; watermarkPath: string; params: ImageWatermarkParams },
    options?: WatermarkOptions,
  ): Promise<{ outputs: string[]; count: number; moved: number }>;

  watermarkVideo(
    input: {
      inPath: string;
      outPath: string;
      watermarkPath: string;
      wmfile2?: string;
      params: VideoWatermarkParams;
    },
    options?: WatermarkOptions,
  ): Promise<{ outPath: string }>;

  detect(input: { inPath: string }, options?: WatermarkOptions): Promise<DetectResult>;

  delogo(
    input: { inPath: string; outPath: string; regions: DetectRegions },
    options?: WatermarkOptions,
  ): Promise<{ outPath: string }>;
}
