import { Hono } from "hono";
import { withRoute } from "../with-route.js";
const pp = new Hono();
pp.get("/", withRoute(async (c, s) => c.json(await s.provider.listProviderProfiles())));
pp.post("/", withRoute(async (c, s) => c.json(await s.provider.createProviderProfile(await c.req.json()), { status: 201 })));
pp.get("/:id", withRoute(async (c, s) => c.json(await s.provider.getProviderProfile(c.req.param("id")))));
pp.patch("/:id", withRoute(async (c, s) => c.json(await s.provider.updateProviderProfile(c.req.param("id"), await c.req.json()))));
pp.delete("/:id", withRoute(async (c, s) => { await s.provider.deleteProviderProfile(c.req.param("id")); return c.json({ ok: true }); }));
pp.post("/:id/test", withRoute(async (c, s) => c.json(await s.provider.testProviderProfile(c.req.param("id")))));
export default pp;
